### ISSUE TITLE
No build system

### ISSUE THREAD

**Issue by SamoZ256** [devjgames/X3D#1]
How can I build this project?

**Comment by devjgames** [comment]
1) To build you will have to create a macOS Framework project called X3D and add the source files from the X3D/X3D folder.

2) If you want to build the tests you will have to create a macOS App project called X3DTest and add the files, folders and resources from X3D/Test and a reference to the project from (1)

**Comment by SamoZ256** [comment]
Are there any plans to have an actual build system? I mean something like CMake

**Comment by devjgames** [comment]
I have no plans to add a CMake build system. Apple complicates things with signing certificates, so the easy thing for me to do is just build using and Xcode project

**Comment by SamoZ256** [comment]
I will try to build using CMake, I don't like using Xcode when I don't have to

**Comment by SamoZ256** [comment]
Seems that using `NSApplicationMain` without Xcode is a pretty bad idea

**Comment by devjgames** [comment]
Builds with Xcode
